title: Using GitHub Actions for CD
tagline: Automate CD with GitHub Actions
description: >-
  This course will walk you through using GitHub Actions to get your code in a
  deployable state once your CI workflows have completed.
template:
  repo: using-github-actions-for-cd-template
  name: using-github-actions-for-cd
before:
  - type: createPullRequest
    title: Setting Up CI
    body: 00.0_Setup-CI.md
    head: ci-workflow
    comments:
      - 00.1_First-CI-Comment.md

steps:
  - title: Location Location Location
    description: Place the CI workflow file in the proper directory
    event: pull_request.synchronize
    actions:
      - type: getTree
        action_id: tree
        recursive: true
        sha: "%payload.pull_request.head.sha%"
      - type: gate
        left: "%actions.tree.data.tree%"
        operator: includes
        right: "path:.github/workflows/ci-workflow.yml"
        else:
          - type: respond
            with: 00.2_CI-Workflow-Fail.md
      - type: mergePullRequest
      - type: deleteBranch
        branch: ci-workflow
      - type: mergeBranch
        head: master
        base: docker-workflow
      - type: createPullRequest
        title: Docker Workflow
        body: 01.0_Building-Docker-Images.md
        head: docker-workflow
        action_id: dockerworkflowpr
        data:
          workflowUrl: "%payload.repository.html_url%/edit/master/.github/workflows/ci-workflow.yml" #not working
      - type: respond
        with: 01.1_Docker-Workflow.md
        issue: Docker Workflow
      - type: respond
        with: 00.4_Next-Pull.md
        issue: Setting Up CI
        data:
          pullURL: "%actions.dockerworkflowpr.data.html_url%"

  - title: Configuring Our CD Flow
    description: Building Our Docker Workflow and Secrets Config
    event: pull_request.synchronize
    actions:
      - type: getTree
        action_id: tree
        recursive: true
        sha: "%payload.pull_request.head.sha%"
      - type: gate
        left: "%actions.tree.data.tree%"
        operator: includes
        right: "path:.github/workflows/cd-workflow.yml"
        else:
          - type: respond
            with: 01.2_Docker-Workflow-Fail.md
      - type: mergePullRequest
      - type: deleteBranch
        branch: docker-workflow
      - type: mergeBranch
        head: master
        base: add-dockerfile
      - type: createPullRequest
        title: Add a Dockerfile
        body: Dockerfile.md
        head: add-dockerfile
        action_id: dockerfile
        comments:
          - 01.3_Configure-Dockerfile.md
      - type: respond
        with: 00.4_Next-Pull.md
        data:
          pullURL: "%actions.dockerfile.data.html_url%"

  - title: Triggering Our Pipeline
    description: Time to see the magic happen
    event: pull_request.synchronize
    actions:
      - type: respond
        with: 01.4_Trigger-Docker-Build.md
  ############################################################
  # Somehow this is currently failingview image here https://i.imgur.com/CQw4fhy.png
  # Looks to be something with a 'respond' type not triggering properly
  ############################################################
  - title: Viewing The Workflow
    description: Verify if the Docker workflow was successful or not
    event: check_suite.completed
    actions:
      - type: gate
        left: "%payload.check_suite.conclusion%"
        operator: ===
        right: "success"
        else:
          - type: respond
            with: 01.5_Check-Suite-Fail.md
            issue: Add a Dockerfile
      - type: respond
        with: 01.6_Success.md
        issue: Add a Dockerfile
      ############################################################
      # The above bug breaks everything below this line, even when
      # Manually merging or closing the PR
      ############################################################
      - type: mergePullRequest
      - type: deleteBranch
        branch: add-dockerfile

  - title: Using the Image
    description: run our image locally
    event: pull_request.closed
    actions:
      - type: gate
        left: "%payload.pull_request.merged%"
      - type: createIssue
        title: Consuming The Newly Created Docker Image
        body: 02.0_Pull-Run-Image.md
      - type: respond
        with: 02.1_Docker-Login.md
      - type: respond
        with: 02.2_Docker-Pull.md
      - type: respond
        with: 02.3_Docker-Run.md
      - type: respond
        with: Done.md
      - type: closeIssue
